# Generated by Django 5.2 on 2025-05-02 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0002_workplacemetadata_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workdesk",
            name="desk_number",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="workdesk",
            name="workplace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workdesk",
                to="administrator.workplacemetadata",
            ),
        ),
        migrations.AlterField(
            model_name="workdeskstatus",
            name="workdesk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status",
                to="administrator.workdesk",
            ),
        ),
    ]
