# Generated by Django 5.2 on 2025-05-02 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administrator",
            "0003_alter_workdesk_desk_number_alter_workdesk_workplace_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workdeskstatus",
            name="workdesk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workdesk",
                to="administrator.workdesk",
            ),
        ),
    ]
