# Generated by Django 5.2 on 2025-05-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0004_alter_workdeskstatus_workdesk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workdeskstatus",
            name="status",
            field=models.CharField(
                choices=[("EMPTY", "EMPTY"), ("WORKING", "WORKING"), ("IDLE", "IDLE")],
                default="EMPTY",
                max_length=10,
            ),
        ),
    ]
