# Generated by Django 5.2 on 2025-05-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0005_alter_workdeskstatus_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="workplacemetadata",
            name="source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
