# Generated by Django 5.2 on 2025-05-05 05:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0006_workplacemetadata_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="workdeskstatus",
            name="unique_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
