# Generated by Django 5.2 on 2025-05-05 05:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0007_workdeskstatus_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workdeskstatus",
            name="unique_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
